name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t react-app .

    - name: Lint in Docker
      run: docker run --rm react-app npm run lint

    - name: Extract Build
      run: |
        docker create --name extract react-app
        docker cp extract:/app/dist ./dist
        docker rm extract

    - name: Deploy
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/${repository}
        # Note: Ensure your 'npm run deploy' points to the './dist' folder
        npm install -g gh-pages
        gh-pages -d dist
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
